version: '3.10'

services:
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - "postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql

networks:
    postgres:
volumes:
    postgres:
  
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
  #     PGADMIN_DEFAULT_PASSWORD: adminpassword
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - 80:80
  #   networks:
  #     - postgres
  #   restart: unless-stopped

# networks:
#   postgres:
#     driver: bridge